// <auto-generated />
using System;
using Booker.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Booker.Domain.Migrations
{
    [DbContext(typeof(BookerDbContext))]
    [Migration("20220819084327_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Booker.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Contact")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            ID = new Guid("3a92ad5c-4b0f-479d-8ae5-3f69fe6b5479"),
                            Contact = 1234852121L,
                            Name = "Carson"
                        },
                        new
                        {
                            ID = new Guid("5ccf1cc9-81b2-4819-a7b7-8debcab9a079"),
                            Contact = 4852618224L,
                            Name = "Meredith"
                        },
                        new
                        {
                            ID = new Guid("66d0d543-45ad-48df-b3c5-20fa37fe0b24"),
                            Contact = 5842016982L,
                            Name = "Arturo"
                        },
                        new
                        {
                            ID = new Guid("2ceb1f4b-fa4d-4375-abe6-a3bec97539df"),
                            Contact = 125874256L,
                            Name = "Gytis"
                        },
                        new
                        {
                            ID = new Guid("37aebf67-bca4-4bea-a48f-fb7e960637a0"),
                            Contact = 4269875136L,
                            Name = "Yan"
                        },
                        new
                        {
                            ID = new Guid("c2902351-2ac8-4cd2-858b-9c25b7af59f8"),
                            Contact = 785129634L,
                            Name = "Peggy"
                        },
                        new
                        {
                            ID = new Guid("e14c7382-2e4e-41fc-9b94-3a4ac7b4579e"),
                            Contact = 78129647L,
                            Name = "Laura"
                        },
                        new
                        {
                            ID = new Guid("2c18c39b-3bc1-4bd4-ab93-937d41b210c3"),
                            Contact = 362035652L,
                            Name = "Nino"
                        });
                });

            modelBuilder.Entity("Booker.Domain.Entities.Movie", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isRented")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            ID = new Guid("c2fad76f-cb31-4141-aaa5-354c66d85546"),
                            CustomerID = new Guid("66d0d543-45ad-48df-b3c5-20fa37fe0b24"),
                            Description = "Moana, daughter of chief Tui, embarks on a journey to return the heart of goddess Te Fitti from Maui, a demigod, after the plants and the fish on her island start dying due to a blight.",
                            Title = "Moana",
                            isRented = true
                        },
                        new
                        {
                            ID = new Guid("370c2e80-5967-44b1-86ae-b213a2a919cd"),
                            Description = "When Peter Venkman, Raymond Stantz and Egon Spengler lose their jobs as scientists, they start an establishment called Ghostbusters to fight the evil ghosts lurking in New York City.",
                            Title = "Ghostbusters",
                            isRented = false
                        },
                        new
                        {
                            ID = new Guid("d4ed3892-008e-4972-9242-48ec14930065"),
                            Description = "James Halliday designs a virtual reality and hides the keys to his fortune in it for a worthy player to find after his death. Wade, a teenager, sets out on a quest to find the keys and the fortune.",
                            Title = "Ready Player One",
                            isRented = false
                        },
                        new
                        {
                            ID = new Guid("c546e6ef-3eb1-43fe-b34f-89987b517152"),
                            Description = "Four years after the destruction of Isla Nublar, dinosaurs now live and hunt alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with history's most fearsome creatures.",
                            Title = "Jurassic World",
                            isRented = false
                        },
                        new
                        {
                            ID = new Guid("ed95b142-1f1f-460e-8445-279f7aff682d"),
                            Description = "Ant-Man is a 2015 American superhero film based on the Marvel Comics characters of the same name: Scott Lang and Hank Pym. Produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures, it is the 12th film in the Marvel Cinematic Universe (MCU).",
                            Title = "Antman",
                            isRented = false
                        });
                });

            modelBuilder.Entity("Booker.Domain.Entities.Movie", b =>
                {
                    b.HasOne("Booker.Domain.Entities.Customer", "Rentee")
                        .WithMany()
                        .HasForeignKey("CustomerID");

                    b.Navigation("Rentee");
                });
#pragma warning restore 612, 618
        }
    }
}
